# Generated by Django 4.1 on 2023-01-31 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodoestacionamento', '0005_clienterotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienterotativo',
            name='valor_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaodoestacionamento.parametros'),
        ),
    ]
